<a href="https://colab.research.google.com/github/IlyaGalyukshev/simple_python/blob/main/np_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import array
import numpy as np

In [ ]:
a = list(range(10))
array.array("i", a)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(a, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.array([range(i, i + 3) for i in [1, 2, 3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3, 5, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.full((3, 5), 4.3)

array([[4.3, 4.3, 4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3, 4.3, 4.3]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3, 3))

array([[0.25458693, 0.15993336, 0.87932174],
       [0.78043588, 0.56971136, 0.43384736],
       [0.21967726, 0.14933904, 0.41050563]])

In [ ]:
np.random.normal(0, 1, (3, 3))

array([[ 0.16743632,  0.60171242, -1.21033267],
       [-0.69924556, -0.40669076,  0.25489859],
       [-1.09882904,  0.57345338,  1.34588519]])

In [ ]:
np.random.randint(0, 10, (2, 3))

array([[0, 2, 3],
       [9, 8, 6]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((4, 6))

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
x = np.random.randint(1, 10, (3, 3, 3))
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.itemsize, "bytes")
print(x.nbytes, f"= {x.size * x.itemsize}")

3
(3, 3, 3)
27
int64
8 bytes
216 = 216


In [ ]:
x[0, 0, -1] = 4.22
x[0, 0, -1]

4

In [ ]:
a = np.arange(10)
a[::2]

array([0, 2, 4, 6, 8])

In [ ]:
print(x[2:,:2,::2])
print(x[2:,:2,::2].shape)

[[[3 7]
  [2 2]]]
(1, 2, 2)


срезы в numpy передаются по ссылке, в отличие от list, срезы которых передаются по значению. чтобы редактирование не изменяло исходный массив, можно использовать copy()

In [ ]:
x_sub = x[2:, :2, ::2].copy()
print(x_sub)
print(x)

[[[3 7]
  [2 2]]]
[[[8 7 4]
  [4 7 7]
  [6 7 7]]

 [[2 8 4]
  [7 6 8]
  [5 5 6]]

 [[3 8 7]
  [2 5 2]
  [5 6 1]]]


In [ ]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x1 = np.arange(5)
print(x1)

print(x1.reshape((1, 5)))
print(x1[np.newaxis, :])

print(x1.reshape((5, 1)))
print(x1[:, np.newaxis])

[0 1 2 3 4]
[[0 1 2 3 4]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
p = np.arange(3)
q = np.arange(3)[::-1]
np.concatenate((p, q, np.arange(1, 4)))

array([0, 1, 2, 2, 1, 0, 1, 2, 3])