<a href="https://colab.research.google.com/github/IlyaGalyukshev/simple_python/blob/main/Python_Data_Science_Handbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import array
import numpy as np

In [ ]:
a = list(range(10))
array.array("i", a)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(a, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.array([range(i, i + 3) for i in [1, 2, 3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3, 5, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.full((3, 5), 4.3)

array([[4.3, 4.3, 4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3, 4.3, 4.3]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3, 3))

array([[0.25458693, 0.15993336, 0.87932174],
       [0.78043588, 0.56971136, 0.43384736],
       [0.21967726, 0.14933904, 0.41050563]])

In [ ]:
np.random.normal(0, 1, (3, 3))

array([[ 0.16743632,  0.60171242, -1.21033267],
       [-0.69924556, -0.40669076,  0.25489859],
       [-1.09882904,  0.57345338,  1.34588519]])

In [ ]:
np.random.randint(0, 10, (2, 3))

array([[0, 2, 3],
       [9, 8, 6]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((4, 6))

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
x = np.random.randint(1, 10, (3, 3, 3))
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.itemsize, "bytes")
print(x.nbytes, f"= {x.size * x.itemsize}")

3
(3, 3, 3)
27
int64
8 bytes
216 = 216


In [ ]:
x[0, 0, -1] = 4.22
x[0, 0, -1]

4

In [ ]:
a = np.arange(10)
a[::2]

array([0, 2, 4, 6, 8])

In [ ]:
print(x[2:,:2,::2])
print(x[2:,:2,::2].shape)

[[[3 7]
  [2 2]]]
(1, 2, 2)


срезы в numpy передаются по ссылке, в отличие от list, срезы которых передаются по значению. чтобы редактирование не изменяло исходный массив, можно использовать copy()

In [ ]:
x_sub = x[2:, :2, ::2].copy()
print(x_sub)
print(x)

[[[3 7]
  [2 2]]]
[[[8 7 4]
  [4 7 7]
  [6 7 7]]

 [[2 8 4]
  [7 6 8]
  [5 5 6]]

 [[3 8 7]
  [2 5 2]
  [5 6 1]]]


In [ ]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x1 = np.arange(5)
print(x1)

print(x1.reshape((1, 5)))
print(x1[np.newaxis, :])

print(x1.reshape((5, 1)))
print(x1[:, np.newaxis])

[0 1 2 3 4]
[[0 1 2 3 4]]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
p = np.arange(3)
q = np.arange(3)[::-1]
np.concatenate((p, q, np.arange(1, 4)))

array([0, 1, 2, 2, 1, 0, 1, 2, 3])

In [10]:
grid = np.random.randint(1, 10, (3, 3))
grid1 = np.random.randint(1, 10, (3, 3))
print(grid)
print(grid1)
np.concatenate((grid, grid1), axis=1)

[[9 1 4]
 [9 6 5]
 [4 8 3]]
[[8 9 7]
 [8 6 1]
 [8 2 4]]


array([[9, 1, 4, 8, 9, 7],
       [9, 6, 5, 8, 6, 1],
       [4, 8, 3, 8, 2, 4]])

In [14]:
print(np.vstack((grid, grid1)))
print()
print(np.hstack((grid, grid1)))
print()
print(np.dstack((grid, grid1)))

[[9 1 4]
 [9 6 5]
 [4 8 3]
 [8 9 7]
 [8 6 1]
 [8 2 4]]

[[9 1 4 8 9 7]
 [9 6 5 8 6 1]
 [4 8 3 8 2 4]]

[[[9 8]
  [1 9]
  [4 7]]

 [[9 8]
  [6 6]
  [5 1]]

 [[4 8]
  [8 2]
  [3 4]]]


In [15]:
np.split(np.arange(10), (3, 5))

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [18]:
x = np.arange(16).reshape((4, 4))
print(x)
print(np.vsplit(x, (1, 2)))
print(np.hsplit(x, (1, 2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [20]:
a, b = np.vsplit(x, (2))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

универсальные функции numpy на несколько порядков ускоряют вычисления за счет векторизации

In [28]:
x = np.arange(4)
np.exp2(np.absolute(((-x // 3 + 1) - 3) * 5))

array([ 1024., 32768., 32768., 32768.])

In [35]:
x = np.random.random((3)) / 100000
print(np.expm1(x))
print(np.exp(x) - 1)

[2.96445137e-06 1.81100320e-06 9.80285506e-06]
[2.96445137e-06 1.81100320e-06 9.80285506e-06]


In [36]:
from scipy import special
special.gamma(x)

array([337330.4688667 , 552180.06237099, 102011.01991753])

при большом количестве элементов out помогает сэкономить много памяти

In [40]:
x = np.arange(5)
y = np.arange(10)
print(y)
np.multiply(x, 10, out=y[::2])
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1 10  3 20  5 30  7 40  9]


метод reduce применяется многократно, пока не останется только один результат. например, суммирует или перемножает все элементы массива.

In [41]:
x = np.arange(10)
np.add.reduce(x)

45

метод accumulate сохраняет все промежуточные шаги в массиве

In [42]:
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

outer выводит результат применения операции ко всем парам элементов двух массивов

In [45]:
np.multiply.outer(x, x)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [52]:
x = np.random.randint(1, 16, (4, 4))
print(x)
np.max(x, axis=0)

[[ 9 11  2 14]
 [11 10  9  2]
 [ 5  9 10  6]
 [12 13  6  8]]


array([12, 13, 10, 14])

head: cannot open 'data/president_heights.csv' for reading: No such file or directory
