<a href="https://colab.research.google.com/github/IlyaGalyukshev/colab/blob/main/VK_education.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 9
b = 9
print(a, b, sep='a')
print('{}, {}'.format(a, b))
print(a is b)
print([1, 2, 3] is [1, 2, 3])

a1 = [1, 2, 3]
a2 = [1, 5, 6]
a1.extend(a2)
print(a1)

9a9
9, 9
True
False
[1, 2, 3, 1, 5, 6]


In [ ]:
import numpy as np

a = np.random.randint(1, 10, (3, 3))
b = np.random.randn(3, 3)
print(a)
print(np.cumsum(a, axis=0))

[[2 2 6]
 [8 2 2]
 [8 4 6]]
[[ 2  2  6]
 [10  4  8]
 [18  8 14]]


array([[-0.3468929 , -0.2354491 ,  0.42708219],
       [ 0.87342756,  0.66250592,  1.05889891],
       [-1.21541164,  0.03559687, -1.09855807]])

In [ ]:
np.save("saved_array", a)
np.load("saved_array.npy")

array([[2, 2, 6],
       [8, 2, 2],
       [8, 4, 6]])

In [ ]:
np.savez("saved_arrays", first=a, second=b)
arch = np.load("saved_arrays.npz")
arch['first']

array([[2, 2, 6],
       [8, 2, 2],
       [8, 4, 6]])

In [ ]:
a = np.arange(10, 501)
np.sum(a * a - 234)

41676571

In [ ]:
import pandas as pd
data = pd.read_csv("/content/orders.csv", sep=',')
data

date  vendor_id  chain_id  city_id         spec  \
0      2019-07-02      40065      7501       23         Суши   
1      2019-08-27      48058     33226       23       Шаурма   
2      2019-09-25      35430     26220       25        Пицца   
3      2019-09-21      56553     38601       23      Шашлыки   
4      2019-09-21      43919     30984       25         Суши   
...           ...        ...       ...      ...          ...   
96113  2019-08-18      44315     31154       24         Суши   
96114  2019-06-15      17528     11182       25        Пицца   
96115  2019-08-19      45351     31679       23  Вьетнамская   
96116  2019-09-26      64209     42525       25         Суши   
96117  2019-09-06      34676     25567       26  Итальянская   

       successful_orders  fail_orders  
0                   54.0          1.0  
1                    0.0          0.0  
2                    2.0          0.0  
3                    1.0          0.0  
4                    6.0          0.0  
...                  ...          ...  
96113                2.0          0.0  
96114               11.0          1.0  
96115                1.0          0.0  
96116                7.0          0.0  
96117                1.0          0.0  

[96118 rows x 7 columns]

In [ ]:
pd.unique(data['city_id'])

array([23, 25, 26, 24])

In [ ]:
pd.unique(data['spec'])
data[data['spec'] == 'Рыба']

date  vendor_id  chain_id  city_id  spec  successful_orders  \
36     2019-08-17      45071     23027       25  Рыба                3.0   
130    2019-07-16      25401     17786       26  Рыба                1.0   
135    2019-06-15       7201      4085       26  Рыба               10.0   
362    2019-08-07      29161     20821       26  Рыба                1.0   
422    2019-09-17       7201      4085       26  Рыба               13.0   
...           ...        ...       ...      ...   ...                ...   
95471  2019-07-31      14558      9089       26  Рыба               32.0   
95595  2019-07-10      16780     10566       25  Рыба                1.0   
95629  2019-08-29      32849     23027       25  Рыба               15.0   
95630  2019-08-30      42795     23027       25  Рыба                9.0   
95977  2019-09-27      16780     10566       25  Рыба                1.0   

       fail_orders  
36             0.0  
130            0.0  
135            0.0  
362            0.0  
422            0.0  
...            ...  
95471          1.0  
95595          0.0  
95629          0.0  
95630          0.0  
95977          0.0  

[1103 rows x 7 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96118 entries, 0 to 96117
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   date               96118 non-null  object 
 1   vendor_id          96118 non-null  int64  
 2   chain_id           96118 non-null  int64  
 3   city_id            96118 non-null  int64  
 4   spec               95733 non-null  object 
 5   successful_orders  96118 non-null  float64
 6   fail_orders        96118 non-null  float64
dtypes: float64(2), int64(3), object(2)
memory usage: 5.1+ MB


In [ ]:
len(pd.unique(data[(data['vendor_id'] == 40065) & (data['successful_orders'] < 20)]['date']))

45

In [6]:
import numpy as np
math_grades = np.array([85, 90, 78, 92, 88, 85, 76, 98, 94, 87])

np.std(math_grades)

6.435060217278468

In [7]:
import scipy.stats as stats

algorithm_a_times = [3.2, 5.1, 4.3, 6.7, 7.9, 4.8, 5.6, 6.2, 5.9]
algorithm_b_times = [2.9, 4.5, 6.1, 5.8, 4.2, 5.3, 4.7, 6.5, 6.8]


stats.mannwhitneyu (algorithm_a_times, algorithm_b_times, alternative='two-sided')

MannwhitneyuResult(statistic=46.0, pvalue=0.6588432549492806)

In [16]:
import scipy.stats as st

mean = np.mean(data)
std = np.std(data)
n = len(data)
se = std / n**0.5

left = mean - st.norm.ppf(.95)*se
right = mean + st.norm.ppf(.95)*se

left

155.22652265140482

In [33]:
import sqlite3
import pandas as pd

connection = sqlite3.connect('/content/my_online_store.db')
cursor = connection.cursor()
query = """select product_id, sum(quantity) from orders group by product_id order by 2 desc"""
# query = """select sum(total_price) from orders"""
# result = cursor.execute(query).fetchall()
# pd.DataFrame(result)
pd.read_sql_query(query, connection)

product_id  sum(quantity)
0           96             21
1           62             19
2           87             18
3           16             18
4           98             16
..         ...            ...
57          50              2
58          94              1
59          12              1
60           7              1
61           4              1

[62 rows x 2 columns]

In [30]:
connection = sqlite3.connect('/content/my_online_store.db')
cursor = connection.cursor()
query = """select * from products where product_id=96"""

pd.read_sql_query(query, connection)

product_id    product_name  category   price
0          96  HFvpNNVhmAUgDZ  Телефоны  154.67